package com.springrest.appointment.model;

import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

import com.springrest.appointment.enums.StudentAppointmentStatus;

@Entity
public class Appointment {

	@Id
    @GeneratedValue(strategy = GenerationType.AUTO) // Auto generated by Hibernate
    private Long id;
	
	@OneToOne
	private Student student;
	
	@OneToOne
	private Course course;
	
	@OneToOne
	private Slots slots;
	
	private LocalDate appointmentDate;
	 
	@Enumerated(EnumType.STRING)
	private StudentAppointmentStatus status;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Slots getSlots() {
		return slots;
	}

	public void setSlots(Slots slots) {
		this.slots = slots;
	}

	public LocalDate getAppointmentDate() {
		return appointmentDate;
	}

	public void setAppointmentDate(LocalDate appointmentDate) {
		this.appointmentDate = appointmentDate;
	}

	public StudentAppointmentStatus getStatus() {
		return status;
	}

	public void setStatus(StudentAppointmentStatus status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "Appointment [id=" + id + ", student=" + student + ", course=" + course + ", slots=" + slots
				+ ", appointmentDate=" + appointmentDate + ", status=" + status + "]";
	}

	
}
